#  测试前端代码
name: test_client_code

on:
    push:
        branches: [client]

jobs:
    build:
      run-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [10.x,12.x,14.x]
      steps:
      - uses: actions/checkout@v2
      - name: set node version
        with:
          node-version: ${{matrix.node-version}}
      - run: |
          # change directory
          cd client/src
          # install packages
          npm install
          # run test
          npm run-srcipt test

